# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/v*
pr:
- master


pool:
  name: Hosted VS2017

steps:
  
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './'
    customCommand: 'run build'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: './'
    customRegistry: 'useFeed'
    publishEndpoint: 'npmjs.org'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))